# blog menu bar
menu:
    home: /
    about: /

blog_name: Forsigner

# avatar path
avatar: images/avatar.png

# favicon path
favicon: images/favicon.ico

# For seo
keywords: 年糕小豆汤,前端,设计,Hexo主题,前端开发,用户体验,设计,vim,neovim,markdown,frontend,design,nodejs,JavaScript,python

link:

# Stats

# Comment setting
duoshuo: yuukocn
