# blog menu bar
menu:
    home: /
    about: /

# avatar path
avatar: /images/avatar.png

# favicon path
favicon: /images/favicon.ico

# For seo
keywords: 年糕小豆汤,前端,设计,Hexo主题,前端开发,用户体验,设计,vim,neovim,markdown,frontend,design,nodejs,JavaScript,python

social:
  - type: email
    name: ooiss@qq.com
    url: mailto:ooiss@qq.com
    target_blank: false
  - type: github
    name: 年糕小豆汤
    url: https://github.com/iamcco
    target_blank: true
  - type: weibo
    name: 豆小汤
    url: http://weibo.com/iamcco
    target_blank: true

link:

# Stats

# Comment setting
duoshuo: yuukocn

# analytics
analytics:
  baidu: df895598ee93a4eedafb515b4186ab2e
